# Generated by Django 6.0.3 on 2026-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_alter_configuration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(blank=True, help_text='Stored value (always a string). Encrypted at rest when is_secret=True; cast to the appropriate type when used.'),
        ),
    ]
