# Generated by Django 6.0.3 on 2026-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_alter_configuration_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='module',
            field=models.CharField(choices=[('general', 'General'), ('integration_ai', 'AI Integration'), ('integration_email', 'Email Integration'), ('integration_sso', 'SSO Integration'), ('integration_jira', 'Jira Integration'), ('security', 'Security'), ('security_password', 'Password Policy'), ('project_approval', 'Project Approval'), ('recharge_contacts', 'Recharge Contacts'), ('board_cards', 'Board Cards')], default='general', help_text='Logical grouping: general, integration_*, security, or security_password.', max_length=30),
        ),
    ]
