# Generated by Django 6.0.3 on 2026-04-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_teams', '0002_deliveryteam_member_count'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='delivery_teams.deliveryteam'),
        ),
        migrations.CreateModel(
            name='ProjectCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborators', to='projects.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_collaborations', to='delivery_teams.deliveryteam')),
            ],
            options={
                'ordering': ['team__name'],
                'unique_together': {('project', 'team')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_projects', through='projects.ProjectCollaborator', to='delivery_teams.deliveryteam'),
        ),
    ]
