# Generated by Django 6.0.3 on 2026-04-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
    ]
