# Generated by Django 6.0.3 on 2026-04-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectestimate_projectestimatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimatehistory',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='projects.projectestimate'),
        ),
    ]
