# Generated by Django 6.0.3 on 2026-04-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0001_initial'),
        ('projects', '0008_alter_projectestimatehistory_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('refined_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_links', to='projects.projectestimate')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_budgets', to='financial_years.financialyear')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project')),
            ],
            options={
                'ordering': ['financial_year__start_date'],
                'unique_together': {('project', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated')], max_length=20)),
                ('previous_allocated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('previous_refined_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('previous_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_allocated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_refined_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='projects.projectbudget')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_history', to='financial_years.financialyear')),
                ('new_estimate_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_history_new', to='projects.projectestimate')),
                ('previous_estimate_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_history_previous', to='projects.projectestimate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_history', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
