# Generated by Django 6.0.3 on 2026-04-15 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_contact_notes'),
        ('projects', '0010_contact_projectcontacthistory_projectcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontacthistory',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_history', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_contact_assignments', to='contacts.contact'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
