# Generated by Django 6.0.3 on 2026-05-19 13:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_follow_comment_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectfollower',
            name='unique_project_follower',
        ),
        migrations.AlterUniqueTogether(
            name='projectfollower',
            unique_together={('project', 'user')},
        ),
    ]
