# Generated by Django 6.0.3 on 2026-04-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
