# Generated by Django 6.0.3 on 2026-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0003_monthly_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
