# Generated by Django 6.0.3 on 2026-04-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Only one location may be the default at a time. Used to pre-select in UI dropdowns.'),
        ),
    ]
