# Generated by Django 6.0.3 on 2026-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_add_onboarding_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='scenario',
            field=models.CharField(choices=[('user_created', 'New User Created'), ('password_reset', 'Password Reset'), ('recharge_forecast', 'Recharge Forecast'), ('recharge_actuals', 'Recharge Actuals'), ('onboarding_submitted', 'Onboarding Submitted'), ('project_approved', 'Project Approved')], max_length=50, unique=True),
        ),
    ]
