from django.core.exceptions import ValidationError
from django.db import models


class Sprint(models.Model):
    """
    A sprint is a fixed-duration planning period within a Financial Year.

    Fields
    ------
    financial_year  : FK to FinancialYear — cascade delete.
    sprint_number   : Positive integer, unique within a FY.
    sprint_name     : Auto-generated from SPRINT_NAME_PREFIX + sprint_number,
                      but can be manually overridden.
    start_date      : Inclusive start date — must fall within the FY window.
    end_date        : Inclusive end date — must fall within the FY window and
                      be >= start_date.
    month           : Auto-calculated from end_date (Jan-Dec).  Stored so filters
                      and grouping never need a date function at query time.
    is_active       : Explicit active flag.  Rather than inferring from today's
                      date, the user (or a future management command) sets this.
                      Allows a sprint to stay "active" a few days after its
                      nominal end while actuals are being closed.
    is_overridden   : True when the user has manually corrected dates that were
                      originally generated by the Run Engine.  Prevents the
                      engine from silently overwriting manual adjustments on
                      subsequent runs.
    notes           : Free-text field for any sprint-level annotations.
    created_at / updated_at : Audit timestamps.
    """

    financial_year = models.ForeignKey(
        'financial_years.FinancialYear',
        on_delete=models.CASCADE,
        related_name='sprints',
    )
    sprint_number = models.PositiveIntegerField()
    sprint_name = models.CharField(max_length=60)
    start_date = models.DateField()
    end_date = models.DateField()
    month = models.CharField(
        max_length=3,
        editable=False,
        help_text="Auto-calculated month (Jan-Dec) from end_date.",
    )
    is_active = models.BooleanField(
        default=False,
        help_text=(
            "Explicitly marks this sprint as the current active sprint. "
            "Set manually or via the Set Active action — not derived from dates "
            "so closing actuals can take a few days after sprint end."
        ),
    )
    is_overridden = models.BooleanField(
        default=False,
        help_text=(
            "True when dates were manually corrected after engine generation. "
            "The Run Engine will skip overridden sprints on subsequent runs."
        ),
    )
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['financial_year', 'sprint_number']
        unique_together = [('financial_year', 'sprint_number')]

    def __str__(self):
        return self.sprint_name

    def save(self, *args, **kwargs):
        if self.end_date:
            self.month = self.end_date.strftime("%b")
        if not self.sprint_name:
            from apps.configurations.services import ConfigurationService
            sprint_prefix = ConfigurationService.get_str("SPRINT_NAME_PREFIX", "Sprint")
            self.sprint_name = f"{sprint_prefix} {self.sprint_number}"
        super().save(*args, **kwargs)

    def clean(self):
        if self.end_date and self.start_date and self.end_date < self.start_date:
            raise ValidationError({
                "end_date": "End date cannot be before start date.",
            })
