# Generated by Django 6.0.3 on 2026-05-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgchartnode',
            name='node_type',
            field=models.CharField(choices=[('member', 'Member'), ('team', 'Team')], default='member', max_length=20),
        ),
    ]
