# Generated by Django 6.0.3 on 2026-04-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.PositiveIntegerField()),
                ('sprint_name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('month', models.CharField(editable=False, help_text='Auto-calculated month (Jan-Dec) from end_date.', max_length=3)),
                ('is_active', models.BooleanField(default=False, help_text='Explicitly marks this sprint as the current active sprint. Set manually or via the Set Active action — not derived from dates so closing actuals can take a few days after sprint end.')),
                ('is_overridden', models.BooleanField(default=False, help_text='True when dates were manually corrected after engine generation. The Run Engine will skip overridden sprints on subsequent runs.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='financial_years.financialyear')),
            ],
            options={
                'ordering': ['financial_year', 'sprint_number'],
                'unique_together': {('financial_year', 'sprint_number')},
            },
        ),
    ]
