# Generated by Django 6.0.3 on 2026-05-17 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the sprint was closed.', null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='User who closed the sprint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='True when the sprint has been formally closed after both forecast and actuals review are complete. Locks further import changes.'),
        ),
    ]
