# Generated by Django 6.0.3 on 2026-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('long_fy', models.CharField(editable=False, help_text='e.g. FY2024-2025', max_length=11)),
                ('short_fy', models.CharField(editable=False, help_text='e.g. FY24-25', max_length=7)),
                ('span_days', models.PositiveIntegerField(default=0, editable=False, help_text='Total calendar days from start_date to end_date (inclusive).')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one financial year may be active at a time.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
