# Generated by Django 6.0.3 on 2026-04-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sub_statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsubstatus',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='projectsubstatus',
            constraint=models.UniqueConstraint(fields=('name', 'main_status'), name='unique_name_per_main_status'),
        ),
        migrations.AddConstraint(
            model_name='projectsubstatus',
            constraint=models.UniqueConstraint(fields=('main_status', 'order'), name='unique_order_per_main_status'),
        ),
    ]
