# Generated by Django 6.0.3 on 2026-04-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryteam',
            name='member_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cached count of active members. Maintained automatically via signals.'),
        ),
    ]
