# Generated by Django 6.0.3 on 2026-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_django_groups_password_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password change. Used for rotation policy enforcement.', null=True),
        ),
    ]
