# Generated by Django 6.0.3 on 2026-05-15 20:25

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_password_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture uploaded by the user.', null=True, upload_to=apps.users.models._avatar_upload_path),
        ),
    ]
