# Generated by Django 6.0.3 on 2026-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('users', '0006_avatar_uuid_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='permission_categories',
            field=models.ManyToManyField(blank=True, related_name='groups', to='permissions.permissioncategory'),
        ),
    ]
