"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(env_path: Path) -> None:
    """Minimal .env loader — sets os.environ from KEY=VALUE lines."""
    if not env_path.exists():
        return
    with open(env_path, encoding='utf-8') as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, val = line.partition('=')
            os.environ.setdefault(key.strip(), val.strip().strip('"').strip("'"))


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_*5td@-q4a^_hbzzya4!y2k2%n!jm%$b7jii+%h3*&o^y$3%#@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.users",
    "apps.delivery_teams",
    "apps.skills",
    "apps.configurations",
    "apps.office_locations",
    "apps.team_roles",
    "apps.employment_types",
    "apps.team_members",
    "apps.public_holidays",
    "apps.member_leaves",
    "apps.financial_years",
    "apps.sprints",
    "apps.sprint_capacity",
    "apps.project_types",
    "apps.project_sub_statuses",
    "apps.programmes",
    "apps.contacts",
    "apps.projects",
    "apps.tags",
    "apps.resource_plans",
    "apps.import",
    "apps.permissions",
    "apps.reporting",
    "apps.sprint_forecast",
    "apps.email_templates",
    "apps.business_units",
    "apps.onboarding",
    "apps.notifications",
    "apps.wins",
    "apps.todos",
    "apps.orgchart",
    "apps.howto",
    "apps.jobs_admin",
    "apps.setup",
    "apps.roadmaps",
    "rest_framework.authtoken",
]

# ── Jobs API ──────────────────────────────────────────────────────────────────
# Set this env var to a strong random string. Use the same value as the
# Authorization header token when calling POST /api/v1/jobs/{name}/run/.
JOB_SERVICE_TOKEN = os.environ.get('JOB_SERVICE_TOKEN', '')

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.setup.middleware.SetupMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.users.middleware.SessionTimeoutMiddleware",
    "apps.users.middleware.AuthRequiredMiddleware",
    "apps.users.middleware.ForcePasswordChangeMiddleware",
    "apps.users.middleware.ModulePermissionMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.users.context_processors.user_perms_js",
                "apps.users.context_processors.app_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Engine selection:
#   DB_ENGINE=sqlite      → SQLite (default, local dev)
#   DB_ENGINE=postgresql  → PostgreSQL (production)
#
# PostgreSQL connection env vars:
#   DB_NAME, DB_USER, DB_HOST, DB_PORT
#
# Password resolution (DB_PASSWORD_SOURCE):
#   env  (default) → DB_PASSWORD env var
#   aws            → AWS Secrets Manager, secret named DB_SECRET_NAME
#                    expects either a plain string or JSON {"password": "…"}
#                    key overridable via DB_SECRET_KEY (default "password")

def _resolve_db_password() -> str:
    source = os.environ.get('DB_PASSWORD_SOURCE', 'env').lower()
    if source == 'aws':
        import json
        import boto3
        from botocore.exceptions import ClientError
        secret_name = os.environ.get('DB_SECRET_NAME', 'resourceplanner/db/password')
        region      = os.environ.get('AWS_DEFAULT_REGION', os.environ.get('AWS_REGION', 'us-east-1'))
        secret_key  = os.environ.get('DB_SECRET_KEY', 'password')
        try:
            client = boto3.client('secretsmanager', region_name=region)
            resp   = client.get_secret_value(SecretId=secret_name)
            raw    = resp.get('SecretString', '')
            try:
                return json.loads(raw).get(secret_key, raw)
            except (json.JSONDecodeError, AttributeError):
                return raw
        except ClientError as exc:
            import logging
            logging.getLogger(__name__).error(
                'Failed to fetch DB password from AWS Secrets Manager (%s): %s',
                secret_name, exc,
            )
            return ''
    return os.environ.get('DB_PASSWORD', '')


_DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite').lower()

if _DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     os.environ.get('DB_NAME',     'resourceplanner'),
            'USER':     os.environ.get('DB_USER',     'postgres'),
            'PASSWORD': _resolve_db_password(),
            'HOST':     os.environ.get('DB_HOST',     'localhost'),
            'PORT':     os.environ.get('DB_PORT',     '5432'),
            'OPTIONS':  {'connect_timeout': 10},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME':   BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "/static/"

# Media files (user uploads, avatars)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Authentication
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}

AUTHENTICATION_BACKENDS = [
    'apps.users.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',  # fallback for admin
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'apps.users.validators.ConfigurationPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours

# Email — all settings (host, port, user, password, from, protocol) are managed
# via the Configurations UI. The backend delegates to ConfigurationService at runtime.
EMAIL_BACKEND = "apps.users.email_backend.ConfigurationEmailBackend"

# ── Logging ───────────────────────────────────────────────────────────────────
# LOG_DIR: override via env var LOG_DIR; defaults to BASE_DIR/logs.
LOG_DIR = Path(os.environ.get('LOG_DIR', str(BASE_DIR / 'logs')))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s — %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[%(levelname)s] %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Rotating log for the Team (delivery_teams) module.
        # Generic pattern — copy this block and update the filename + logger name
        # to add rotating logs for other modules.
        'delivery_teams_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'delivery_teams.log'),
            'maxBytes': int(os.environ.get('LOG_MAX_BYTES', str(10 * 1024 * 1024))),  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Root logger — warnings and above to console
        '': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        # Django internals
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # All app loggers default to console at INFO
        'apps': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Team module — console + rotating file
        'apps.delivery_teams': {
            'handlers': ['console', 'delivery_teams_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Jobs
        'jobs': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "apps.users.authentication.BearerTokenAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "apps.users.permissions.ModulePermission",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}
