# Generated by Django 6.0.3 on 2026-04-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprints', '0001_initial'),
        ('team_members', '0002_alter_teammember_default_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('holiday_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('net_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='sprints.sprint')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacities', to='team_members.teammember')),
            ],
            options={
                'ordering': ['sprint', 'team_member', 'net_capacity'],
                'unique_together': {('sprint', 'team_member')},
            },
        ),
    ]
