# Generated by Django 6.0.3 on 2026-05-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_teams', '0002_deliveryteam_member_count'),
        ('programmes', '0001_initial'),
        ('projects', '0013_projectview'),
        ('sprint_forecast', '0004_alter_sprintconfirmedrow_options_and_more'),
        ('sprints', '0002_sprint_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('estimate_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimate_value_with_contingency', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost_till_date', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_actuals', to='delivery_teams.deliveryteam')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborating_project_actuals', to='delivery_teams.deliveryteam')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_actuals', to='projects.projectlabel')),
                ('last_updated_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_actuals', to='sprints.sprint')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_actuals', to='programmes.programme')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actuals', to='projects.project')),
            ],
            options={
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSprintActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('project_actuals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_actuals', to='sprint_forecast.projectactuals')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sprint_actuals', to='sprints.sprint')),
            ],
            options={
                'ordering': ['sprint__sprint_number'],
                'constraints': [models.UniqueConstraint(fields=('project_actuals', 'sprint'), name='unique_project_sprint_actual')],
            },
        ),
    ]
