# Generated by Django 6.0.3 on 2026-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrole',
            name='is_assignable',
            field=models.BooleanField(default=False, help_text='Marks this role as eligible for automatic work assignment in the resource planning engine.'),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Only one role may be the default at a time. Used to pre-select in UI dropdowns.'),
        ),
    ]
