# Generated by Django 6.0.3 on 2026-04-03 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_teams', '0001_initial'),
        ('employment_types', '0001_initial'),
        ('office_locations', '0002_officelocation_is_default'),
        ('skills', '0001_initial'),
        ('team_roles', '0002_teamrole_is_assignable_teamrole_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('display_name', models.CharField(help_text='Auto-generated as "Last Name, First Name". Override if needed.', max_length=165)),
                ('email_address', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')])),
                ('start_date', models.DateField(help_text='Date the member joined / became available for planning.')),
                ('end_date', models.DateField(blank=True, help_text='Date the member leaves. Null means currently active.', null=True)),
                ('default_holidays', models.PositiveIntegerField(default=20, help_text='Holiday days per financial year. Defaults to the system DEFAULT_HOLIDAYS.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_employment_type', to='employment_types.employmenttype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_location', to='office_locations.officelocation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_role', to='team_roles.teamrole')),
                ('skills', models.ManyToManyField(blank=True, related_name='member_skills', to='skills.skill')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_team', to='delivery_teams.deliveryteam')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_on', models.DateField(help_text='Effective date of the team change.')),
                ('note', models.TextField(blank=True, help_text='Optional: Reason for the move.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery_teams.deliveryteam')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='team_members.teammember')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery_teams.deliveryteam')),
            ],
            options={
                'ordering': ['-moved_on', '-created_at'],
            },
        ),
    ]
