# Generated by Django 6.0.3 on 2026-04-03 17:32

import apps.team_members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='default_holidays',
            field=models.PositiveIntegerField(default=apps.team_members.models.get_default_holidays, help_text='Holiday days per financial year. Defaults to the system DEFAULT_HOLIDAYS.'),
        ),
    ]
