# Generated by Django 6.0.3 on 2026-04-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_members', '0002_alter_teammember_default_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of leave (inclusive).')),
                ('end_date', models.DateField(help_text='Last day of leave (inclusive). Must be >= start_date.')),
                ('is_half_day', models.BooleanField(default=False, help_text='True when the leave covers only half a working day. Only valid when start_date == end_date.')),
                ('half_day_period', models.CharField(blank=True, choices=[('AM', 'Morning (AM)'), ('PM', 'Afternoon (PM)')], help_text='Which half of the day is taken. Required when is_half_day=True.', max_length=2, null=True)),
                ('days', models.DecimalField(decimal_places=2, editable=False, help_text="Working days consumed (auto-calculated, excludes weekends and public holidays for the member's location).", max_digits=6)),
                ('note', models.TextField(blank=True, default='', help_text='Optional free-text note about the leave.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(help_text='The team member this leave record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='team_members.teammember')),
            ],
            options={
                'ordering': ['start_date', 'member'],
            },
        ),
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The specific calendar date that is a leave day.')),
                ('is_half_day', models.BooleanField(default=False, help_text='True when only half a day is consumed on this date.')),
                ('half_day_period', models.CharField(blank=True, choices=[('AM', 'Morning (AM)'), ('PM', 'Afternoon (PM)')], max_length=2, null=True)),
                ('member', models.ForeignKey(help_text='The team member whose availability is affected.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to='team_members.teammember')),
                ('leave', models.ForeignKey(help_text='The parent leave record that produced this day.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to='member_leaves.memberleave')),
            ],
            options={
                'ordering': ['date', 'member'],
                'unique_together': {('member', 'date', 'leave')},
            },
        ),
    ]
