# Generated by Django 6.0.3 on 2026-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberleave',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional free-text note about the leave.', null=True),
        ),
    ]
