# Generated by Django 6.0.3 on 2026-04-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_teams', '0002_deliveryteam_member_count'),
        ('financial_years', '0001_initial'),
        ('programmes', '0001_initial'),
        ('projects', '0013_projectview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('FY', 'Financial Year'), ('PROJECT', 'Project'), ('PROGRAMME', 'Programme'), ('TEAM', 'Team')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='resource_plans.resourceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='resource_plans.resourceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_group', models.UUIDField(db_index=True, unique=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_plan_scopes', to='financial_years.financialyear')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_plan_scopes', to='programmes.programme')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_plan_scopes', to='projects.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_plan_scopes', to='delivery_teams.deliveryteam')),
            ],
            options={
                'ordering': ['plan_group'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_group', models.UUIDField(db_index=True)),
                ('version', models.PositiveIntegerField()),
                ('threshold_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_versions', to='resource_plans.resourceplanversion')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='resource_plans.resourceplan')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('plan_group', 'version')},
            },
        ),
    ]
