# Generated by Django 6.0.3 on 2026-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
