# Generated by Django 6.0.3 on 2026-04-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0001_initial'),
        ('resource_plans', '0002_resourceplan_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceplan',
            name='status',
        ),
        migrations.AddField(
            model_name='resourceplan',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='resource_plan', to='financial_years.financialyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceplanversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
    ]
