# Generated by Django 6.0.3 on 2026-05-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plans', '0009_plan_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEngineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mode', models.CharField(choices=[('VALIDATE', 'Validate Only'), ('FULL', 'Full Run')], default='VALIDATE', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=100, null=True)),
                ('progress_pct', models.PositiveIntegerField(default=0)),
                ('include_current_sprint', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('validation_result', models.JSONField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='planphasesegment',
            name='unique_phase_segment_order',
        ),
        migrations.AddField(
            model_name='planenginejob',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_jobs', to='resource_plans.resourceplan'),
        ),
        migrations.AddField(
            model_name='planenginejob',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_jobs', to='resource_plans.resourceplanversion'),
        ),
    ]
