# Generated by Django 6.0.3 on 2026-05-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plans', '0010_plan_engine_job'),
        ('sprints', '0001_initial'),
        ('team_members', '0002_alter_teammember_default_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_auto', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_leaves', to='sprints.sprint')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_leaves', to='team_members.teammember')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_leaves', to='resource_plans.resourceplanversion')),
            ],
            options={
                'ordering': ['sprint__sprint_number', 'team_member__last_name'],
                'unique_together': {('version', 'team_member', 'sprint')},
            },
        ),
    ]
