# Generated by Django 6.0.3 on 2026-05-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plans', '0011_placeholder_leave'),
        ('sprints', '0001_initial'),
        ('team_members', '0002_alter_teammember_default_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='planenginejob',
            name='steps_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResourcePlanMemberCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('holiday_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('placeholder_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('net_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_capacities', to='sprints.sprint')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_capacities', to='team_members.teammember')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_capacities', to='resource_plans.resourceplanversion')),
            ],
            options={
                'ordering': ['sprint__sprint_number', 'team_member__last_name'],
                'unique_together': {('version', 'team_member', 'sprint')},
            },
        ),
    ]
