# Generated by Django 6.0.3 on 2026-05-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_teams', '0002_deliveryteam_member_count'),
        ('resource_plans', '0014_allocation_engine'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourceplanplaceholderengineer',
            name='unique_placeholder_slot',
        ),
        migrations.AlterUniqueTogether(
            name='resourceplanplaceholderengineer',
            unique_together={('version', 'team', 'phase', 'slot_number')},
        ),
    ]
