# Generated by Django 6.0.3 on 2026-05-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plans', '0017_placeholder_engineers'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='placeholderengineer',
            name='unique_ph_version_seq',
        ),
        migrations.RemoveConstraint(
            model_name='placeholderengineerabsence',
            name='unique_ph_absence_sprint',
        ),
        migrations.AlterUniqueTogether(
            name='placeholderengineer',
            unique_together={('version', 'sequence_number')},
        ),
        migrations.AlterUniqueTogether(
            name='placeholderengineerabsence',
            unique_together={('placeholder_engineer', 'sprint')},
        ),
    ]
