# Generated by Django 6.0.3 on 2026-05-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plans', '0018_remove_placeholderengineer_unique_ph_version_seq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_allocation_days', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_members', models.PositiveIntegerField(blank=True, null=True)),
                ('total_projects', models.PositiveIntegerField(blank=True, null=True)),
                ('total_sprints', models.PositiveIntegerField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='resource_plans.resourceplanversion')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanSnapshotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.PositiveIntegerField()),
                ('sprint_name', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('programme_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phase_name', models.CharField(blank=True, max_length=200, null=True)),
                ('assignment_type', models.CharField(max_length=20)),
                ('includes_in_budget', models.BooleanField(default=True)),
                ('days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_override', models.BooleanField(default=False)),
                ('is_placeholder', models.BooleanField(default=False)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='resource_plans.resourceplansnapshot')),
            ],
            options={
                'ordering': ['sprint_number', 'team_name', 'member_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanSnapshotCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.PositiveIntegerField()),
                ('sprint_name', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=200)),
                ('working_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('holiday_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('placeholder_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('net_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='resource_plans.resourceplansnapshot')),
            ],
            options={
                'ordering': ['sprint_number', 'team_name', 'member_name'],
            },
        ),
    ]
