# Generated by Django 6.0.3 on 2026-05-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plans', '0020_placeholder_engineer_global_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENGINE_RUN', 'Engine Run'), ('ALLOCATION_OVERRIDE', 'Allocation Override'), ('PLACEHOLDER_OVERRIDE', 'Placeholder Override'), ('CONFLICT_RESOLVED', 'Conflict Resolved'), ('STATUS_CHANGED', 'Status Changed'), ('PLAN_CLONED', 'Plan Cloned'), ('CONFIG_CHANGED', 'Config Changed')], max_length=30)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engine_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='resource_plans.planenginejob')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='resource_plans.resourceplan')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='resource_plans.resourceplanversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
