# Generated by Django 6.0.3 on 2026-04-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office_locations', '0002_officelocation_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The calendar date of the public holiday.')),
                ('name', models.CharField(help_text='Name of the public holiday, e.g. "Christmas Day".', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='The office location this holiday applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='public_holidays', to='office_locations.officelocation')),
            ],
            options={
                'ordering': ['date', 'location'],
                'unique_together': {('location', 'date')},
            },
        ),
    ]
