# Generated by Django 6.0.3 on 2026-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_mention', 'Comment Mention'), ('project_approved', 'Project Approved'), ('recharge_forecast', 'Recharge Forecast'), ('recharge_actuals', 'Recharge Actuals'), ('project_follow', 'Project Update'), ('monthly_wins_phase1', 'Monthly Wins Phase 1'), ('monthly_wins_phase2', 'Monthly Wins Phase 2')], max_length=50),
        ),
    ]
